#ifndef _HTTPPROXYRESPONSE_H_
#define _HTTPPROXYRESPONSE_H_

/**
 * HTTP response generated by proxy server
 */
struct HTTPProxyResponse {
    /**
     * HTTP version, e.g. "HTTP/1.1"
     */
    char http_ver[10];
    /**
     * HTTP status code
     */
    char status[4];
    /**
     * sentence to describe the returned HTTP status
     */
    char phrase[100];
};

extern void HTTPProxyResponse_construct_err_response(const char* http_ver, const int status_code, struct HTTPProxyResponse* result);
extern void HTTPProxyResponse_write_headers(struct HTTPProxyResponse* response, char* result);
extern void HTTPProxyResponse_write_err_payload(struct HTTPProxyResponse* response, const char* desc, char* result);

#endif
