#ifndef _HTTPPROXYRESPONSE_H_
#define _HTTPPROXYRESPONSE_H_

/**
 * HTTP response generated by proxy server
 */
struct HTTPProxyResponse {
    /**
     * HTTP version, e.g. "HTTP/1.1"
     */
    char http_ver[10];
    /**
     * HTTP status code
     */
    char status[4];
    /**
     * sentence to describe the returned HTTP status
     */
    char phrase[100];
};

extern void HTTPProxyResponse_to_string(struct HTTPProxyResponse* response, char* result);

#endif
